---
- name: Add external providers
  ovirt_external_providers:
    auth: "{{ ovirt_auth }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    type: "{{ item.type }}"
    url: "{{ item.url }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    tenant: "{{ item.tenant }}"
    auth_url: "{{ item.auth_url }}"
    data_center: "{{ item.data_center | default(omit) }}"
  with_items:
    - "{{ external_providers | default([]) }}"
  tags:
    - external_providers
