---
galaxy_info:
  author: Petr Kubica
  description: Role to install packages required for deploying oVirt engine.
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: 2.3

  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora

  galaxy_tags: [ovirt, rhv, rhev, virtualization]

dependencies: []
