---
- name: Add clusters
  # TODO: Change when Ansible 2.4 is released:
  # ovirt_clusters:
  ovirt_clusters_internal_24:
    auth: "{{ ovirt_auth }}"
    state: "{{ item.state | default(omit) }}"
    name: "{{ item.name }}"
    data_center: "{{ data_center_name }}"
    cpu_type: "{{ item.cpu_type | default('Intel Conroe Family') }}"
    compatibility_version: "{{ compatibility_version }}"
    ballooning: "{{ item.ballooning | default(profiles[item.profile | default('_')].ballooning) | default(omit) }}"
    description: "{{ item.description| default(profiles[item.profile | default('_')].description) | default(omit) }}"
    ksm: "{{ item.ksm | default(profiles[item.profile | default('_')].ksm) | default(omit) }}"
    ksm_numa: "{{ item.ksm_numa | default(profiles[item.profile | default('_')].ksm_numa) | default(omit) }}"
    host_reason: "{{ item.host_reason | default(profiles[item.profile | default('_')].host_reason) | default(omit) }}"
    vm_reason: "{{ item.vm_reason | default(profiles[item.profile | default('_')].vm_reason) | default(omit) }}"
    memory_policy: "{{ item.memory_policy | default(profiles[item.profile | default('_')].memory_policy) | default('disabled') }}"
    migration_policy: "{{ item.migration_policy | default(profiles[item.profile | default('_')].migration_policy) | default(omit) }}"
    scheduling_policy: "{{ item.scheduling_policy | default(profiles[item.profile | default('_')].scheduling_policy) | default(omit) }}"
    ha_reservation: "{{ item.ha_reservation | default(profiles[item.profile | default('_')].ha_reservation) | default(omit) }}"
    fence_enabled: "{{ item.fence_enabled | default(profiles[item.profile | default('_')].fence_enabled) | default(omit) }}"
    fence_skip_if_connectivity_broken: "{{ item.fence_skip_if_connectivity_broken | default(profiles[item.profile | default('_')].fence_skip_if_connectivity_broken) | default(omit) }}"
    fence_skip_if_sd_active: "{{ item.fence_skip_if_sd_active | default(profiles[item.profile | default('_')].fence_skip_if_sd_active) | default(omit) }}"
    mac_pool:  "{{ item.mac_pool | default(omit) }}"
  with_items:
    - "{{ clusters | default([]) }}"
  tags:
    - clusters
